name: Run test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MGORM_CI: "true"
    services:
      mysql-mock:
        image: gcr.io/mgorm-305807/mysql-mock
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v2

      - uses: codecov/codecov-action@v1
        flags: unittests
        name: codecov-gsorm
        fail_ci_if_error: true
        verbose: true

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
