name: Test and coverage

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MGORM_CI: "true"
    services:
      mysql-mock:
        image: gcr.io/mgorm-305807/mysql-mock
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
